### ISSUE TITLE
digital_read always returns false

### ISSUE THREAD

**Issue by deadprogram** [Bluebie/littlewire.rb#3]
Hi!

I am trying to run the littlewire.rb using a digispark that I have loaded littlewire on, using littlewire_v12.hex that I downloaded from http://littlewire.cc/downloads.html.

I was able to get the blinky example working fine using :pin1:

``` ruby
require 'littlewire'

wire = LittleWire.connect
wire.pin_mode :pin1 => :input

loop do
  wire.digital_write(:pin1, true) # set the LED on for half a second
  sleep 0.5
  wire.digital_write(:pin1, false) # set the LED off for half a second
  sleep 0.5
end
```

I then attached a switch with a pull-down resistor to pin1, along with +5 and GND (http://arduino.cc/en/tutorial/button circuit), and have been trying this code:

``` ruby
require 'littlewire'

wire = LittleWire.connect
wire.pin_mode :pin1 => :input

loop do
  puts wire.digital_read(:pin1)
  sleep 0.5
end
```

No matter which pin I connect to (sticking to p1/p2/p5 on the digispark, of course) digital_read always returns false. When I am plugged into :pin1 the LED on the digispark lights up as I would expect from pushing the button, so it would appear I have continuity.

Any ideas?

**Comment by Bluebie** [comment]
First up, as you're using a Digispark rather than the LittleWire device, I recommend you use the termonology :ds0, :ds1, :ds2, :ds5 to refer to the pins, as this will match the naming of the pins on the digispark. Next up, I just did a test and you're totally right - this is broken. I'll add an example containing this code, and fix the gem so it actually works. Sorry about that!

``` ruby
# Read the state of a button connecting between pin 0 and ground on a digispark
require 'littlewire'
wire = LittleWire.connect

wire.pin_mode ds0: :input
wire.digital_write ds0: true
puts "Pin 0 is " + wire.digital_read(:ds0).inspect
```

**Comment by deadprogram** [comment]
OMG I love you! Thank you for such awesome support!!

**Comment by deadprogram** [comment]
Also, thanks for explaining the pin name/numbering. I probably want to use just the integer identifying the pin, as I am wrapping littlewire.rb into an Artoo adaptor (http://artoo.io/)

Thanks again for the help, and all your cool microcontroller work, it is appreciated!

**Comment by Bluebie** [comment]
Fixed it. `gem install littlewire` for the latest update. Thanks for the bug report!

**Comment by Bluebie** [comment]
Also Artoo looks amazing! I like it a lot. I've been thinking a lot about those sorts of things. Did you know someone managed to get mruby running on an arduino due? check it out! https://github.com/kyab/mruby-arduino

mruby opens up so many extremely neat possibilities ^_^

**Comment by deadprogram** [comment]
Thank you very much for the nice compliment on Artoo. Agreed, MRuby is exciting, the future of Ruby is getting really interesting for sure!
